#os: Visual Studio 2015

install:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build: off

test_script:
  # Run the project tests
  - hello.py
  - echo "no output above :(  but it works when we explicitly use python below!"
  - python hello.py
